### ISSUE TITLE
"browser prefixors (opt in, large performance hit)"?

### ISSUE THREAD

**Issue by ghost** [ericwooley/react-in-style#11]
Why is there a large performance hit?  Just curious.  :)

**Comment by ericwooley** [comment]
There is a performance hit because auto prefixer will grab data from caniuse.com which is a network request, so there will not be any prefixes until that returns. After the first time it should go faster (I think).

https://github.com/postcss/autoprefixer-core

The reason I put the (performance hit) is to warn people not to just use autoprefixer if you are only using standard css which doesn't need to be prefixed.

In the unit test applying styles without autoprefix, was almost instant, with autoprefix, on the first time took as much as 50ms, depending on the network request, but was almost instant after that.

I am going to leave this open because I want to investigate how I can speed autoprefixer up.

**Comment by ghost** [comment]
Ah, I see.  Thanks for the explanation!

**Comment by ericwooley** [comment]
Autoprefixer has been removed. For now there is no replacement functionality, but I am thinking I might make an array of properties that need prefixing.
